### PR TITLE
Conflict resolved

### PR DESCRIPTION
**Pull request by mmillerks**
Hopefully able to merge now -- says no conflicts

### CODE REVIEW

**Review by mosesb1 — CHANGES_REQUESTED** [review]
Line 68 on navbar.jsx has the equal signs from the merge conflict. you will need to get rid of those so it doesnt cause an error when you run the code.

**Comment by mmillerks** [comment]
Done  and saved. Do I need to submit a new pull request?

**Review by mosesb1 — CHANGES_REQUESTED** [review]
I see equal signs on line 65 now. You also have a merge conflict because I just merged Orlando's code. Run a git pull upstream dev before you fix the equal signs and then you should be good.

**Comment by mmillerks** [comment]
pull upstream - done 
changes - done 
ok now??

**Pull request merged**
